### PR TITLE
Adding Cocoapods image.

### PR DESCRIPTION
**Pull request by danbev**
Suggestion for adding a cocoapods image. 
See [README.md](https://github.com/danbev/aerogear-ios-sync/tree/cocoapods-image#aerogear-ios-differential-synchronization-client-engine--) to see what this would look like.

### CODE REVIEW

**Comment by danbev** [comment]
@cvasilak @corinnekrych What do you think, is this worth adding? If so I'll do a PR for aerogear-ios-sync-client as well.

**Comment by cvasilak** [comment]
looks good @danbev go for it 👍

**Comment by matzew** [comment]
+1

On Tue, Feb 10, 2015 at 8:07 PM, Christos Vasilakis <
notifications@github.com> wrote:

> looks good @danbev <https://github.com/danbev> go for it [image: 👍]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-ios-sync/pull/9#issuecomment-73761675>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by cvasilak** [comment]
thank you @danbev :rocket: landed on https://github.com/aerogear/aerogear-ios-sync/commit/2a88c01fdbb64877556c4242a0d73e83684e88bc

**Pull request merged**
