### PR TITLE
further changes to json-patch lib as discovered by working with the demo imply

### PR DESCRIPTION
**Pull request by cvasilak**
done for [https://issues.jboss.org/browse/AGIOS-356](AGIOS-356)

utilised by the demo in https://github.com/aerogear/aerogear-ios-sync-demo/pull/3

### CODE REVIEW

**Comment by danbev** [comment]
@cvasilak I've run out of time today, but will review tomorrow morning.

**Comment by danbev** [comment]
:+1: Apart for the comments above.

**Comment by corinnekrych** [comment]
@cvasilak I have created a PR: https://github.com/cvasilak/aerogear-ios-sync/pull/1
with a change proposal. 

I think leaving the PatchMessage a protocol (like we have for Diff and Edit) and making struct implementing this protocol would be more 'Swift'

wdyt?

**Comment by cvasilak** [comment]
@corinnekrych I really like this change :+1: thank you!

(have also [updated ios-client](https://github.com/cvasilak/aerogear-ios-sync-client/commit/e9fcc5156a87ebbeba11af27d266ddc459c3a382 and added the associated type constraint in-there too)

tested with demo app worked great

**Comment by cvasilak** [comment]
@danbev thank you!  have updated based on your comments

**Comment by corinnekrych** [comment]
+1

**Comment by corinnekrych** [comment]
183d2284440b54a0eacc42eb91287c1612777772

landed

**Pull request closed without merging**
