### PR TITLE
sync core documentation

### PR DESCRIPTION
**Pull request by corinnekrych**
Adding source code documentation similar to Java one
@cvasilak mind to review please?

### CODE REVIEW

**Comment by cvasilak** [comment]
@corinnekrych used ```jazzy version: 0.1.2``` latest and noticed some hiccups:

*ClientSyncEngine.swift*
the code block described in the comments is wrongly formatted.
let's further add a small description on the vars 'synchronizer' and 'datastore' 
```params``` on some methods are wrongly formatted    

*ClientSynchronizer.swift*
I think it will be nice if we can add in the class description a link to the source code of the concrete implementations [JsonPatchSynchronizer](https://github.com/aerogear/aerogear-ios-sync/blob/master/AeroGearSync-JSONPatch/JsonPatchSynchronizer.swift) and [DiffMatchPatchSynchronizer](https://github.com/aerogear/aerogear-ios-sync/blob/master/AeroGearSync-DiffMatchPatch/DiffMatchPatchSynchronizer.swift)
```params``` on some methods are wrongly formatted 

*Difference.swift*
 the license is visible and shouldn't be there

**Comment by corinnekrych** [comment]
I fixed the issues around params and returns.
Is there a way to do links @cvasilak?
not sure also what to use for code formatting too. I'm open to proposals.

**Comment by cvasilak** [comment]
@corinnekrych for links have opened [PR#4](https://github.com/corinnekrych/aerogear-ios-sync/pull/4)

Regarding, the code-formatting seems to be a bug in 'jazzy', and can't output multiline code-block, opened issue [jazzy/issues/172](https://github.com/realm/jazzy/issues/172)

after PR is merged :+1:

**Comment by corinnekrych** [comment]
Thanks @cvasilak !
I've merged it!

**Comment by cvasilak** [comment]
landed https://github.com/aerogear/aerogear-ios-sync/commit/bc6aec7dffbaef4758eade153d662c883620404b

**Pull request closed without merging**
